# Generated by Django 5.2.5 on 2025-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notesapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
